openapi: 3.0.0
info:
  title: Map Resources Service
  description: Service to provide data and meta-data for any map related resources.
  version: 0.0.1

servers:
  - url: http://localhost:8082/
    description: Local Development Server

paths:
  /health:
    get:
      summary: Health check
      description: Shallow health check. Reports only the status of this service without consideration of any dependencies.
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
  /map/tile/{z}/{x}/{y}:
    get:
      summary: Get Map Tile at Coordinates (z, x, y)
      parameters:
            - name: z
              in: path
              description: Zoom level
              required: true
              schema:
                type: integer
                format: int32
            - name: x
              in: path
              description: X coordinate
              required: true
              schema:
                type: integer
                format: int32
            - name: y
              in: path
              description: Y coordinate
              required: true
              schema:
                type: integer
                format: int32
      responses:
        '200':
          description: Map Tile
          content:
            image/png:
              schema:
                type: string
                format: binary
components:
  schemas:
    Provider:
      type: string
      enum:
        - discord
    HealthCheckResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - healthy
            - unhealthy
        version:
          type: string
        date:
          type: string
          format: date-time
