name: Github Actions Runtime Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/github-actions-container/Dockerfile'
      - '.github/workflows/actions-container-runtime.yml'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: infrastructure/github-actions-container/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/github-actions-imagimaps:latest

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: botagar/github-actions-imagimaps:latest
      options: --user 1001
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Check foundational setup
        run: |
          echo "Pre-Test"
          echo "Running from: [$(pwd)]"
          echo "Running as user: [$(whoami)]"
          echo "user info: [$(id)]"
          echo "kernel info: [$(uname -a)]"
          echo "OS info: [$(cat /etc/os-release)]"
          echo "PATH: [${PATH}]"

      - name: Check tooling exists
        run: |
          echo "Running tooling tests"
          echo "node version [$(node --version)]"
          echo "npm version [$(npm --version)]"
          echo "pnpm version [$(pnpm --version)]"
          echo "git version [$(git --version)]"
          echo "docker version [$(docker --version)]"
          echo "docker-compose version [$(docker-compose --version)]"

      - name: Check Git Configuration
        run: |
          echo "What's in my current directory?"
          ls -la
          echo "Checking git status"
          git status
          echo "Checking git config"
          git config --list
