name: Build and Deploy Backend Services

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'services/**'
  #     - '.github/workflows/services.yml'
  #     - '.github/actions/imagimaps-service/**'
  #     - '.github/actions/service-bnd/**'

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    container:
      image: botagar/github-actions-imagimaps
      options: --user 1001
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories }}

    steps:
    - uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        dir_names: true
        dir_names_max_depth: 2
        dir_names_exclude_current_dir: true
        json: true
        quotepath: false

    - name: 'Set output in the matrix format'
      id: set-output
      run: |
          echo "changed_directories={"dir":${{ steps.changed-files.outputs.all_changed_files }}}" >> $GITHUB_OUTPUT
          {
            echo "| Variable Set        | Value               |"
            echo "|--------------------- |---------------------|"
            echo "| Changed Directories | ${{ steps.changed-files.outputs.all_changed_files }} |"
          } >> $GITHUB_STEP_SUMMARY

  build_and_deploy_service:
    if: ${{ needs.detect_changes.outputs.changed_directories != '' }}
    needs: detect_changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect_changes.outputs.changed_directories)}}
    container:
      image: botagar/github-actions-imagimaps
      options: --user 1001
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Test Composite Action
      uses: ./.github/actions/composite-test
      with:
        service_dir: ${{ matrix.dir }}

    - name: Build Service
      if: startsWith(matrix.dir, 'services/')
      uses: ./.github/actions/service-builder
      with:
        service_dir: ${{ matrix.dir }}
      env:
        AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DEBUG: true

    - name: Deploy Service
      if: startsWith(matrix.dir, 'services/')
      uses: ./.github/actions/service-deploy
      with:
        service_dir: ${{ matrix.dir }}
      env:
        AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DEBUG: true
