name: Infra Destroy (Soft)

on:
  schedule:
  - cron: '45 13 * * *' # 23:45 AEST (1:45pm UTC)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  dev-webapp-infra:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Bootstrap WebApp Infrastructure
      id: webapp-infra
      uses: Imagimaps/common-actions/.github/actions/s3-static-site@main
      with:
        domain: imagimaps.com
        environment: development
        environment_short_name: dev
        aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        aws_region: ${{ vars.AWS_REGION }}
        destroy: true
