name: Infra Create

on:
  # schedule:
  # - cron: "0 21 * * *" # 07:00 AEST (9pm UTC)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  dev-webapp-infra:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9
          terraform_wrapper: false

      - name: Bootstrap WebApp Infrastructure
        id: webapp-infra
        uses: Imagimaps/common-actions/.github/actions/s3-static-site@main
        with:
          domain: imagimaps.com
          environment: development
          environment_short_name: dev
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}

  dev-bff-infra:
    runs-on: ubuntu-latest
    environment: development
    env:
      SERVICE_NAME: webapp-bff
      SERVICE_PATH_IDENTIFIER: bff

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9
          terraform_wrapper: false

      - name: Bootstrap Infra for Webapp BFF
        uses: Imagimaps/common-actions/.github/actions/bootstrap-service@main
        with:
          service_name: ${{ env.SERVICE_NAME }}
          service_path_identifier: ${{ env.SERVICE_PATH_IDENTIFIER }}
          environment: development
          environment_short_name: dev
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          artifacts_aws_account_id: ${{ secrets.ARTIFACTS_AWS_ACCOUNT_ID }}
          artifacts_aws_role_arn: ${{ secrets.ARTIFACTS_AWS_ROLE_ARN }}
          aws_region: ${{ vars.AWS_REGION }}
